services:
  postgres:
    image: postgres:16
    container_name: auth-postgres
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: auth-keycloak
    command:
      - start-dev
      - --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: authdb
      KC_DB_USERNAME: authuser
      KC_DB_PASSWORD: authpass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    ports:
      - "9091:8080"
    volumes:
      - ./realm-export:/opt/keycloak/d2ata/import
    depends_on:
      - postgres

volumes:
  postgres_data:
